spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    username: sa
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    platform: h2
    password: ''
  h2:
    console:
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
